# Generated by Django 2.1.7 on 2019-04-30 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_auto_20190430_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='read_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
